import express from "express";

import { authenticateUser } from "../middleware/authMiddleware.js";
import { sendEmailOtp, verifyEmailOtp } from "../controller/OtpController.js";
import { login, logout, passwordVerification, register, resetPassword, sendResetLink, updateTwoFA, updateTwoFaSet } from "../controller/user/AuthController.js";
import { changePassword, getReferralLink, getSecurityQuestion, loginHistory, securityQuestion, updateBio, updateProfileImage, updateUsername, userDetail } from "../controller/user/UserController.js";
import { addressVerification, getAddressVerification, getIdDetails, storeAddress } from "../controller/user/AddressVerificationController.js";
import { singelUpload, upload, uploadAttachments } from "../middleware/upload.js";
import { addUpiDetails, getPaymentDetails, getUpiDetails, storePaymentDetails } from "../controller/user/PaymentController.js";
import { formData, validateBio, validateChangePassword, validateSecurityQuestions, validateUsername } from "../middleware/validation.js";
import { uploadImage } from "./adminRoutes.js";
import { createCryptoAd, getCryptoAd, getFavoriteCryptoOffer, getMyCryptoAd, toggleFavoriteCryptoOffer, updateAllCryptoAdIsActive, updateCryptoAd, updateCryptoAdIsActive } from "../controller/user/CryptoAdController.js";
import { getAllNotifications, getPerticularNotification, markAsRead } from "../controller/user/NotificationController.js";
import { getParticularTicket } from "../controller/admin/supportTicketController.js";
import { buyerUpdateTrade, cancelTrade, getTradeFeedback, getTradeHistory, giveFeedback, initiateTrade, updateDispute, updateTradeFeedback } from "../controller/user/TradeController.js";
import { closeTicket, getParticularTickets, getTickets, replySupportTicket, storeTicket } from "../controller/user/UserSupportTicketController.js";
import { getTransactionDetails, sendAsset } from "../controller/user/TransactionController.js";
import { createWeb3Wallet, decryptedData, fetchUserByUsernameAndAddress, getWalletKeyPhrase, getWeb3WalletDetails, updateWeb3Wallet } from "../controller/user/Web3WalletController.js";
import { sendWelcomeEmail } from "../controller/EmailController.js";
import { getReport, getUsersReport, storeReport } from "../controller/ReportController.js";
const router = express.Router();
router.post("/auth/register",formData, register);
router.post("/auth/login", formData, login);
router.post("/verify-email-otp", authenticateUser, verifyEmailOtp);
router.post("/send-email-otp", authenticateUser, sendEmailOtp);
router.get("/user-details", authenticateUser, userDetail);
router.get("/get-referral-link", authenticateUser, getReferralLink);
router.get("/login-history", authenticateUser, loginHistory);
router.post("/address/address-verification", authenticateUser, upload.fields([{ name: "front_document", maxCount: 1 }, { name: "back_document", maxCount: 1 }]), addressVerification);
router.get("/address/get-address-verification", authenticateUser, getAddressVerification);
router.post("/address/id-verification", authenticateUser, upload.fields([{ name: "document_front_image", maxCount: 1 }, { name: "document_back_image", maxCount: 1 }]), storeAddress);
router.get("/address/get-id-verification-details", authenticateUser, getIdDetails);
router.post("/payment-details/add-payment-details", formData, authenticateUser, storePaymentDetails);
router.get("/payment-details/get-payment-details", authenticateUser, getPaymentDetails);
router.post("/payment-details/add-upi-details", authenticateUser, singelUpload.single("qr_code"), addUpiDetails);
router.get("/payment-details/get-upi-details", authenticateUser, getUpiDetails);
router.post("/update-username", formData, authenticateUser, validateUsername, updateUsername);
router.post("/change-password", formData, authenticateUser, validateChangePassword, changePassword);
router.post("/update-bio", formData, authenticateUser, validateBio, updateBio);
router.post("/security-questions", authenticateUser, securityQuestion);
router.get("/security-questions", authenticateUser, getSecurityQuestion);
router.post("/update-profile-image", uploadImage.single("image"), authenticateUser, updateProfileImage);
router.get("/crypto-advertisement/my-crypto-ad", authenticateUser, getMyCryptoAd);
router.post("/crypto-advertisement/create-crypto-ad", formData, authenticateUser, createCryptoAd);
router.get("/crypto-advertisement/crypto-ad", authenticateUser, getCryptoAd);
router.post("/crypto-advertisement/toggle-cryptoAd-active", formData, authenticateUser, updateCryptoAdIsActive);
router.post("/crypto-advertisement/toggle-all-cryptoAd-active", formData, authenticateUser, updateAllCryptoAdIsActive);
router.post("/crypto-advertisement/update-crypto-ad", formData, authenticateUser, updateCryptoAd);
router.post("/crypto-advertisement/toggle-favorite-cryptoOffer", formData, authenticateUser, toggleFavoriteCryptoOffer);
router.get("/crypto-advertisement/get-favorite-offer", formData, authenticateUser, getFavoriteCryptoOffer);
router.get("/notifications", formData, authenticateUser, getAllNotifications);
router.get("/notification/:id", formData, authenticateUser, getPerticularNotification);
router.patch("/mark-as-read", formData, authenticateUser, markAsRead);
router.post("/trade/initiate-trade", formData, authenticateUser, initiateTrade);
router.get("/trade/get-trade-history", authenticateUser, getTradeHistory);
router.post("/trade/give-feedback", formData, authenticateUser, giveFeedback);
router.get("/trade/get-trade-feedback", formData, authenticateUser, getTradeFeedback);
router.post("/trade/update-trade-feedback", formData, authenticateUser, updateTradeFeedback);
router.post("/trade/cancel-trade", formData, authenticateUser, cancelTrade);
router.post("/trade/update-trade-dispute", formData, authenticateUser, updateDispute);
router.post("/support-tickets/store-ticket", authenticateUser, uploadAttachments.array("attachment[]", 5), storeTicket);
router.get("/support-tickets/get-tickets", authenticateUser, getTickets);
router.get("/support-tickets/get-particular-ticket/:id", authenticateUser, getParticularTickets);
router.post("/support-tickets/reply-support-ticket", authenticateUser, uploadAttachments.array("attachment[]", 5), replySupportTicket);
router.post("/support-tickets/close-ticket", formData, authenticateUser, closeTicket);
router.get("/transaction/get-transaction", authenticateUser, getTransactionDetails);
router.post("/transaction/send-asset", formData, authenticateUser, sendAsset);
router.post("/web3-wallet/create-web3-wallet", formData, authenticateUser, createWeb3Wallet);
router.get("/web3-wallet/get-walletKeyPhrase", authenticateUser, getWalletKeyPhrase);
router.post("/web3-wallet/decrypt-data", formData, authenticateUser, decryptedData);
router.get("/web3-wallet/get-web3-wallet", authenticateUser, getWeb3WalletDetails);
router.get("/web3-wallet/get-user-detail", authenticateUser, fetchUserByUsernameAndAddress);
router.post("/web3-wallet/update-web3-wallet", formData, authenticateUser, updateWeb3Wallet);
router.post("/trade/buyer-update-trade", uploadImage.single("image"), authenticateUser, buyerUpdateTrade);
router.post("/send-welcome-email", authenticateUser, sendWelcomeEmail);
router.post("/report/store-report", formData, authenticateUser, storeReport);
router.get("/report/get-report", authenticateUser, getReport);
router.get("/admin/report/get-report", authenticateUser, getUsersReport);
router.post("/auth/update-2fa",formData, authenticateUser, updateTwoFA);
router.post("/auth/update-2fa-set",formData, authenticateUser, updateTwoFaSet);
router.post("/auth/forgot-password",formData, sendResetLink);
router.post("/auth/reset-password",formData, resetPassword);
router.post("/auth/password-verification",formData,authenticateUser, passwordVerification);
router.delete("/auth/logout",authenticateUser, logout);



export default router;
